"""Execution models for tracking generated artifacts and agent work outputs."""
from datetime import datetime
from typing import Optional, TYPE_CHECKING
from enum import Enum
from sqlalchemy import String, Integer, DateTime, ForeignKey, Text, JSON, Boolean
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class ArtifactType(str, Enum):
    """Types of generated artifacts."""
    CODE = "code"
    DOCUMENT = "document"
    TEMPLATE = "template"
    FIGMA_PROMPT = "figma_prompt"
    USER_STORY = "user_story"
    SOCIAL_POST = "social_post"
    EMAIL_TEMPLATE = "email_template"
    SPREADSHEET = "spreadsheet"
    MEETING_AGENDA = "meeting_agenda"
    ARCHITECTURE = "architecture"


class ExecutionStatus(str, Enum):
    """Status of an execution."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"


class GeneratedArtifact(Base):
    """Artifacts generated by AI agents (code, docs, templates, etc.)."""
    
    __tablename__ = "generated_artifacts"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign keys
    startup_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("startups.id"), nullable=False, index=True
    )
    
    # Artifact details
    agent_name: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    artifact_type: Mapped[str] = mapped_column(String(50), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Extra data
    language: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # For code: python, typescript, etc.
    file_extension: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    extra_data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False, index=True
    )
    
    def __repr__(self) -> str:
        return f"<GeneratedArtifact(id={self.id}, type={self.artifact_type}, title={self.title})>"


class ExecutionLog(Base):
    """Log of agent execution actions."""
    
    __tablename__ = "execution_logs"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    startup_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("startups.id"), nullable=False, index=True
    )
    
    # Execution details
    agent_name: Mapped[str] = mapped_column(String(50), nullable=False)
    action_type: Mapped[str] = mapped_column(String(50), nullable=False)  # generate_code, create_doc, etc.
    status: Mapped[str] = mapped_column(String(20), default="pending")
    
    # Input/Output
    input_data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    output_data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Timing
    started_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    def __repr__(self) -> str:
        return f"<ExecutionLog(id={self.id}, agent={self.agent_name}, action={self.action_type})>"
