"""Export API routes."""
import logging
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import AgentLog, Startup
from app.agents import ProductAgent, FinanceAgent, MarketingAgent, TechAgent

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/startup/{startup_id}/export", tags=["Export"])


async def get_latest_agent_output(db: AsyncSession, startup_id: int, agent_name: str) -> dict[str, Any]:
    """Retrieve the latest output for a specific agent and startup."""
    result = await db.execute(
        select(AgentLog)
        .where(AgentLog.startup_id == startup_id)
        .where(AgentLog.agent_name == agent_name)
        .order_by(desc(AgentLog.created_at))
        .limit(1)
    )
    log = result.scalar_one_or_none()
    if not log:
        # Return empty dict instead of confusing error if one agent failed but others succeeded
        logger.warning(f"No data found for {agent_name} agent for startup {startup_id}")
        return {}
    return log.output_json


def generate_master_plan_md(
    startup: Startup,
    product: dict,
    tech: dict,
    marketing: dict,
    finance: dict
) -> str:
    """Combine all agent outputs into a Master Startup Plan."""
    md = f"# Startup Master Plan: {startup.domain}\n"
    md += f"**Goal:** {startup.goal}\n\n"
    
    # 1. Executive Summary (Product Core)
    core = product.get("core_concept", {})
    md += "## 1. Executive Summary\n"
    md += f"**Problem:** {core.get('problem_statement', 'N/A')}\n"
    md += f"**Solution:** {core.get('solution_overview', 'N/A')}\n"
    md += f"**Elevator Pitch:** {core.get('elevator_pitch', 'N/A')}\n\n"
    
    # 2. Product Strategy
    md += "## 2. Product Strategy (MVP)\n"
    for feature in product.get("mvp_features", []):
        md += f"- **{feature.get('title')}**: {feature.get('description')}\n"
    
    # 3. Technical Architecture
    stack = tech.get("tech_stack", {})
    md += "\n## 3. Technical Architecture\n"
    md += f"- **Frontend:** {', '.join(stack.get('frontend', []))}\n"
    md += f"- **Backend:** {', '.join(stack.get('backend', []))}\n"
    md += f"- **Database:** {', '.join(stack.get('database', []))}\n"
    md += f"- **Infrastructure:** {', '.join(stack.get('infrastructure', []))}\n"
    
    # 4. Go-to-Market
    launch = marketing.get("launch_strategy", {})
    md += "\n## 4. Go-to-Market Strategy\n"
    md += f"**Phase:** {launch.get('phase', 'Launch').title()} (Target: {launch.get('target_date_days_from_now')} days)\n"
    md += "**Key Channels:**\n"
    for ch in launch.get("channels", []):
        md += f"- {ch}\n"
        
    # 5. Financial Overview
    budget = finance.get("budget_allocation", {})
    runway = finance.get("runway", {})
    md += "\n## 5. Financial Overview\n"
    md += f"**Total Estimated Budget:** ${budget.get('total_estimated')}\n"
    md += f"**Projected Runway:** {runway.get('months')} months\n"
    md += f"**Burn Rate:** ${finance.get('burn_rate', {}).get('monthly')}/month\n"
    
    md += "\n---\n*CONFIDENTIAL - Generated by StartupOps AI Co-Founders*"
    return md


@router.get("/prd")
async def export_prd(
    startup_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Download Product Requirements Document (markdown)."""
    data = await get_latest_agent_output(db, startup_id, "product")
    
    agent = ProductAgent()
    content = agent.generate_prd_markdown(data)
    
    return Response(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": "attachment; filename=prd.md"}
    )


@router.get("/budget")
async def export_budget(
    startup_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Download Budget Allocation (CSV)."""
    data = await get_latest_agent_output(db, startup_id, "finance")
    
    agent = FinanceAgent()
    content = agent.generate_budget_csv(data)
    
    return Response(
        content=content,
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=budget.csv"}
    )


@router.get("/calendar")
async def export_calendar(
    startup_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Download Launch Calendar (ICS)."""
    data = await get_latest_agent_output(db, startup_id, "marketing")
    
    agent = MarketingAgent()
    content = agent.generate_launch_calendar_ics(data)
    
    return Response(
        content=content,
        media_type="text/calendar",
        headers={"Content-Disposition": "attachment; filename=launch_calendar.ics"}
    )


@router.get("/posts")
async def export_social_posts(
    startup_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Download Social Media Drafts (txt)."""
    data = await get_latest_agent_output(db, startup_id, "marketing")
    
    agent = MarketingAgent()
    content = agent.generate_social_posts_txt(data)
    
    return Response(
        content=content,
        media_type="text/plain",
        headers={"Content-Disposition": "attachment; filename=social_posts.txt"}
    )


@router.get("/architecture")
async def export_architecture(
    startup_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Download Tech Architecture (Markdown)."""
    data = await get_latest_agent_output(db, startup_id, "tech")
    if not data:
        raise HTTPException(status_code=404, detail="Tech agent data not found")
        
    agent = TechAgent()
    content = agent.generate_architecture_md(data)
    
    return Response(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": "attachment; filename=architecture.md"}
    )


@router.get("/master-plan")
async def export_master_plan(
    startup_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Download Master Startup Plan (Markdown)."""
    # Fetch all data in parallel could be better, but sequential is fine for now
    product_data = await get_latest_agent_output(db, startup_id, "product")
    tech_data = await get_latest_agent_output(db, startup_id, "tech")
    marketing_data = await get_latest_agent_output(db, startup_id, "marketing")
    finance_data = await get_latest_agent_output(db, startup_id, "finance")
    
    # Get startup details
    result = await db.execute(select(Startup).where(Startup.id == startup_id))
    startup = result.scalar_one_or_none()
    if not startup:
        raise HTTPException(status_code=404, detail="Startup not found")
        
    content = generate_master_plan_md(startup, product_data, tech_data, marketing_data, finance_data)
    
    return Response(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": "attachment; filename=startup_master_plan.md"}
    )
