export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#0a0a0f] text-gray-300 p-8 md:p-12">
            <div className="max-w-3xl mx-auto space-y-8">
                <div className="border-b border-white/10 pb-8">
                    <h1 className="text-4xl font-bold text-white mb-4">Terms of Service</h1>
                    <p className="text-gray-400">Last updated: January 28, 2026</p>
                </div>

                <article className="prose prose-invert prose-violet max-w-none">
                    <h3>1. Introduction</h3>
                    <p>Welcome to StartupOps. By accessing our website and using our AI-powered startup creation tools, you agree to be bound by these Terms of Service.</p>

                    <h3>2. Acceptable Use</h3>
                    <p>You agree to use StartupOps only for lawful purposes. You are prohibited from violating any laws, infringing on intellectual property, or causing harm to our infrastructure.</p>

                    <h3>3. User Accounts</h3>
                    <p>To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your account credentials.</p>

                    <h3>4. AI Generated Content</h3>
                    <p>Content generated by our AI agents is provided "as-is". While we strive for accuracy, AI models can hallucinate. You should verify critical business information.</p>

                    <h3>5. Subscription & Billing</h3>
                    <p>Premium features require a paid subscription. Payments are non-refundable except as required by law. We reserve the right to change pricing with notice.</p>

                    <h3>6. Limitation of Liability</h3>
                    <p>StartupOps is not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>

                    <h3>7. Contact</h3>
                    <p>If you have questions about these terms, please contact us at legal@startupops.ai.</p>
                </article>

                <div className="pt-8 border-t border-white/10">
                    <a href="/settings" className="text-violet-400 hover:text-violet-300 transition-colors">← Back to Settings</a>
                </div>
            </div>
        </div>
    );
}
